image: node:20

stages:
  - install
  - lint_common
  - test_common
  - lint_user_services
  - test_user_services

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm install
  - pnpm common build

lint_common_job:
  stage: lint_common
  script:
    - pnpm common lint

test_common_job:
  stage: test_common
  script:
    - pnpm common test

lint_user_services_job:
  stage: lint_user_services
  script:
    - pnpm user lint

test_user_services_job:
  stage: test_user_services
  script:
    - pnpm user test
