image: node:20

stages:
  - install
  - lint
  - test
  - build

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm install
  - pnpm common build

lint_common_job:
  stage: lint
  script:
    - pnpm common lint

test_common_job:
  stage: test
  script:
    - pnpm common test

build_common_job:
  stage: build
  script:
    - pnpm common build

lint_user_services_job:
  stage: lint
  script:
    - pnpm user lint

test_user_services_job:
  stage: test
  script:
    - pnpm user test

build_user_services_job:
  stage: build
  script:
    - pnpm user build

lint_analytics_services_job:
  stage: lint
  script:
    - pnpm analytics lint

test_analytics_services_job:
  stage: test
  script:
    - pnpm analytics test

build_analytics_services_job:
  stage: build
  script:
    - pnpm analytics build

lint_gateway_services_job:
  stage: lint
  script:
    - pnpm gateway lint

test_gateway_services_job:
  stage: test
  script:
    - pnpm gateway test

build_gateway_services_job:
  stage: build
  script:
    - pnpm gateway build
